/*
Flowy Client API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiExecuteJobPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiExecuteJobPost200Response{}

// ApiExecuteJobPost200Response struct for ApiExecuteJobPost200Response
type ApiExecuteJobPost200Response struct {
	JobId NullableString `json:"jobId"`
	Error NullableString `json:"error"`
}

type _ApiExecuteJobPost200Response ApiExecuteJobPost200Response

// NewApiExecuteJobPost200Response instantiates a new ApiExecuteJobPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiExecuteJobPost200Response(jobId NullableString, error_ NullableString) *ApiExecuteJobPost200Response {
	this := ApiExecuteJobPost200Response{}
	this.JobId = jobId
	this.Error = error_
	return &this
}

// NewApiExecuteJobPost200ResponseWithDefaults instantiates a new ApiExecuteJobPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiExecuteJobPost200ResponseWithDefaults() *ApiExecuteJobPost200Response {
	this := ApiExecuteJobPost200Response{}
	return &this
}

// GetJobId returns the JobId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiExecuteJobPost200Response) GetJobId() string {
	if o == nil || o.JobId.Get() == nil {
		var ret string
		return ret
	}

	return *o.JobId.Get()
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiExecuteJobPost200Response) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobId.Get(), o.JobId.IsSet()
}

// SetJobId sets field value
func (o *ApiExecuteJobPost200Response) SetJobId(v string) {
	o.JobId.Set(&v)
}

// GetError returns the Error field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiExecuteJobPost200Response) GetError() string {
	if o == nil || o.Error.Get() == nil {
		var ret string
		return ret
	}

	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiExecuteJobPost200Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// SetError sets field value
func (o *ApiExecuteJobPost200Response) SetError(v string) {
	o.Error.Set(&v)
}

func (o ApiExecuteJobPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiExecuteJobPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobId"] = o.JobId.Get()
	toSerialize["error"] = o.Error.Get()
	return toSerialize, nil
}

func (o *ApiExecuteJobPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobId",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiExecuteJobPost200Response := _ApiExecuteJobPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiExecuteJobPost200Response)

	if err != nil {
		return err
	}

	*o = ApiExecuteJobPost200Response(varApiExecuteJobPost200Response)

	return err
}

type NullableApiExecuteJobPost200Response struct {
	value *ApiExecuteJobPost200Response
	isSet bool
}

func (v NullableApiExecuteJobPost200Response) Get() *ApiExecuteJobPost200Response {
	return v.value
}

func (v *NullableApiExecuteJobPost200Response) Set(val *ApiExecuteJobPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiExecuteJobPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiExecuteJobPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiExecuteJobPost200Response(val *ApiExecuteJobPost200Response) *NullableApiExecuteJobPost200Response {
	return &NullableApiExecuteJobPost200Response{value: val, isSet: true}
}

func (v NullableApiExecuteJobPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiExecuteJobPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


