/*
Flowy Client API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiImportToolPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiImportToolPost200Response{}

// ApiImportToolPost200Response struct for ApiImportToolPost200Response
type ApiImportToolPost200Response struct {
	ToolId string `json:"toolId"`
}

type _ApiImportToolPost200Response ApiImportToolPost200Response

// NewApiImportToolPost200Response instantiates a new ApiImportToolPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiImportToolPost200Response(toolId string) *ApiImportToolPost200Response {
	this := ApiImportToolPost200Response{}
	this.ToolId = toolId
	return &this
}

// NewApiImportToolPost200ResponseWithDefaults instantiates a new ApiImportToolPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiImportToolPost200ResponseWithDefaults() *ApiImportToolPost200Response {
	this := ApiImportToolPost200Response{}
	return &this
}

// GetToolId returns the ToolId field value
func (o *ApiImportToolPost200Response) GetToolId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToolId
}

// GetToolIdOk returns a tuple with the ToolId field value
// and a boolean to check if the value has been set.
func (o *ApiImportToolPost200Response) GetToolIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToolId, true
}

// SetToolId sets field value
func (o *ApiImportToolPost200Response) SetToolId(v string) {
	o.ToolId = v
}

func (o ApiImportToolPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiImportToolPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["toolId"] = o.ToolId
	return toSerialize, nil
}

func (o *ApiImportToolPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"toolId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiImportToolPost200Response := _ApiImportToolPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiImportToolPost200Response)

	if err != nil {
		return err
	}

	*o = ApiImportToolPost200Response(varApiImportToolPost200Response)

	return err
}

type NullableApiImportToolPost200Response struct {
	value *ApiImportToolPost200Response
	isSet bool
}

func (v NullableApiImportToolPost200Response) Get() *ApiImportToolPost200Response {
	return v.value
}

func (v *NullableApiImportToolPost200Response) Set(val *ApiImportToolPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiImportToolPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiImportToolPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiImportToolPost200Response(val *ApiImportToolPost200Response) *NullableApiImportToolPost200Response {
	return &NullableApiImportToolPost200Response{value: val, isSet: true}
}

func (v NullableApiImportToolPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiImportToolPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


