/*
Flowy Client API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiExecuteJobPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiExecuteJobPostRequest{}

// ApiExecuteJobPostRequest struct for ApiExecuteJobPostRequest
type ApiExecuteJobPostRequest struct {
	ToolPath string `json:"tool_path"`
	JobPath *string `json:"job_path,omitempty"`
	Outdir *string `json:"outdir,omitempty"`
	Basedir *string `json:"basedir,omitempty"`
	ClientWorkDir string `json:"clientWorkDir"`
	UseContainer *bool `json:"use_container,omitempty"`
	MoveOutput *string `json:"move_output,omitempty"`
}

type _ApiExecuteJobPostRequest ApiExecuteJobPostRequest

// NewApiExecuteJobPostRequest instantiates a new ApiExecuteJobPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiExecuteJobPostRequest(toolPath string, clientWorkDir string) *ApiExecuteJobPostRequest {
	this := ApiExecuteJobPostRequest{}
	this.ToolPath = toolPath
	this.ClientWorkDir = clientWorkDir
	return &this
}

// NewApiExecuteJobPostRequestWithDefaults instantiates a new ApiExecuteJobPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiExecuteJobPostRequestWithDefaults() *ApiExecuteJobPostRequest {
	this := ApiExecuteJobPostRequest{}
	return &this
}

// GetToolPath returns the ToolPath field value
func (o *ApiExecuteJobPostRequest) GetToolPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToolPath
}

// GetToolPathOk returns a tuple with the ToolPath field value
// and a boolean to check if the value has been set.
func (o *ApiExecuteJobPostRequest) GetToolPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToolPath, true
}

// SetToolPath sets field value
func (o *ApiExecuteJobPostRequest) SetToolPath(v string) {
	o.ToolPath = v
}

// GetJobPath returns the JobPath field value if set, zero value otherwise.
func (o *ApiExecuteJobPostRequest) GetJobPath() string {
	if o == nil || IsNil(o.JobPath) {
		var ret string
		return ret
	}
	return *o.JobPath
}

// GetJobPathOk returns a tuple with the JobPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiExecuteJobPostRequest) GetJobPathOk() (*string, bool) {
	if o == nil || IsNil(o.JobPath) {
		return nil, false
	}
	return o.JobPath, true
}

// HasJobPath returns a boolean if a field has been set.
func (o *ApiExecuteJobPostRequest) HasJobPath() bool {
	if o != nil && !IsNil(o.JobPath) {
		return true
	}

	return false
}

// SetJobPath gets a reference to the given string and assigns it to the JobPath field.
func (o *ApiExecuteJobPostRequest) SetJobPath(v string) {
	o.JobPath = &v
}

// GetOutdir returns the Outdir field value if set, zero value otherwise.
func (o *ApiExecuteJobPostRequest) GetOutdir() string {
	if o == nil || IsNil(o.Outdir) {
		var ret string
		return ret
	}
	return *o.Outdir
}

// GetOutdirOk returns a tuple with the Outdir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiExecuteJobPostRequest) GetOutdirOk() (*string, bool) {
	if o == nil || IsNil(o.Outdir) {
		return nil, false
	}
	return o.Outdir, true
}

// HasOutdir returns a boolean if a field has been set.
func (o *ApiExecuteJobPostRequest) HasOutdir() bool {
	if o != nil && !IsNil(o.Outdir) {
		return true
	}

	return false
}

// SetOutdir gets a reference to the given string and assigns it to the Outdir field.
func (o *ApiExecuteJobPostRequest) SetOutdir(v string) {
	o.Outdir = &v
}

// GetBasedir returns the Basedir field value if set, zero value otherwise.
func (o *ApiExecuteJobPostRequest) GetBasedir() string {
	if o == nil || IsNil(o.Basedir) {
		var ret string
		return ret
	}
	return *o.Basedir
}

// GetBasedirOk returns a tuple with the Basedir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiExecuteJobPostRequest) GetBasedirOk() (*string, bool) {
	if o == nil || IsNil(o.Basedir) {
		return nil, false
	}
	return o.Basedir, true
}

// HasBasedir returns a boolean if a field has been set.
func (o *ApiExecuteJobPostRequest) HasBasedir() bool {
	if o != nil && !IsNil(o.Basedir) {
		return true
	}

	return false
}

// SetBasedir gets a reference to the given string and assigns it to the Basedir field.
func (o *ApiExecuteJobPostRequest) SetBasedir(v string) {
	o.Basedir = &v
}

// GetClientWorkDir returns the ClientWorkDir field value
func (o *ApiExecuteJobPostRequest) GetClientWorkDir() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientWorkDir
}

// GetClientWorkDirOk returns a tuple with the ClientWorkDir field value
// and a boolean to check if the value has been set.
func (o *ApiExecuteJobPostRequest) GetClientWorkDirOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientWorkDir, true
}

// SetClientWorkDir sets field value
func (o *ApiExecuteJobPostRequest) SetClientWorkDir(v string) {
	o.ClientWorkDir = v
}

// GetUseContainer returns the UseContainer field value if set, zero value otherwise.
func (o *ApiExecuteJobPostRequest) GetUseContainer() bool {
	if o == nil || IsNil(o.UseContainer) {
		var ret bool
		return ret
	}
	return *o.UseContainer
}

// GetUseContainerOk returns a tuple with the UseContainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiExecuteJobPostRequest) GetUseContainerOk() (*bool, bool) {
	if o == nil || IsNil(o.UseContainer) {
		return nil, false
	}
	return o.UseContainer, true
}

// HasUseContainer returns a boolean if a field has been set.
func (o *ApiExecuteJobPostRequest) HasUseContainer() bool {
	if o != nil && !IsNil(o.UseContainer) {
		return true
	}

	return false
}

// SetUseContainer gets a reference to the given bool and assigns it to the UseContainer field.
func (o *ApiExecuteJobPostRequest) SetUseContainer(v bool) {
	o.UseContainer = &v
}

// GetMoveOutput returns the MoveOutput field value if set, zero value otherwise.
func (o *ApiExecuteJobPostRequest) GetMoveOutput() string {
	if o == nil || IsNil(o.MoveOutput) {
		var ret string
		return ret
	}
	return *o.MoveOutput
}

// GetMoveOutputOk returns a tuple with the MoveOutput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiExecuteJobPostRequest) GetMoveOutputOk() (*string, bool) {
	if o == nil || IsNil(o.MoveOutput) {
		return nil, false
	}
	return o.MoveOutput, true
}

// HasMoveOutput returns a boolean if a field has been set.
func (o *ApiExecuteJobPostRequest) HasMoveOutput() bool {
	if o != nil && !IsNil(o.MoveOutput) {
		return true
	}

	return false
}

// SetMoveOutput gets a reference to the given string and assigns it to the MoveOutput field.
func (o *ApiExecuteJobPostRequest) SetMoveOutput(v string) {
	o.MoveOutput = &v
}

func (o ApiExecuteJobPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiExecuteJobPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tool_path"] = o.ToolPath
	if !IsNil(o.JobPath) {
		toSerialize["job_path"] = o.JobPath
	}
	if !IsNil(o.Outdir) {
		toSerialize["outdir"] = o.Outdir
	}
	if !IsNil(o.Basedir) {
		toSerialize["basedir"] = o.Basedir
	}
	toSerialize["clientWorkDir"] = o.ClientWorkDir
	if !IsNil(o.UseContainer) {
		toSerialize["use_container"] = o.UseContainer
	}
	if !IsNil(o.MoveOutput) {
		toSerialize["move_output"] = o.MoveOutput
	}
	return toSerialize, nil
}

func (o *ApiExecuteJobPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tool_path",
		"clientWorkDir",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiExecuteJobPostRequest := _ApiExecuteJobPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiExecuteJobPostRequest)

	if err != nil {
		return err
	}

	*o = ApiExecuteJobPostRequest(varApiExecuteJobPostRequest)

	return err
}

type NullableApiExecuteJobPostRequest struct {
	value *ApiExecuteJobPostRequest
	isSet bool
}

func (v NullableApiExecuteJobPostRequest) Get() *ApiExecuteJobPostRequest {
	return v.value
}

func (v *NullableApiExecuteJobPostRequest) Set(val *ApiExecuteJobPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiExecuteJobPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiExecuteJobPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiExecuteJobPostRequest(val *ApiExecuteJobPostRequest) *NullableApiExecuteJobPostRequest {
	return &NullableApiExecuteJobPostRequest{value: val, isSet: true}
}

func (v NullableApiExecuteJobPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiExecuteJobPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


