/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the Runtime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Runtime{}

// Runtime struct for Runtime
type Runtime struct {
	CustomNet *string `json:"custom_net,omitempty"`
}

// NewRuntime instantiates a new Runtime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuntime() *Runtime {
	this := Runtime{}
	return &this
}

// NewRuntimeWithDefaults instantiates a new Runtime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuntimeWithDefaults() *Runtime {
	this := Runtime{}
	return &this
}

// GetCustomNet returns the CustomNet field value if set, zero value otherwise.
func (o *Runtime) GetCustomNet() string {
	if o == nil || IsNil(o.CustomNet) {
		var ret string
		return ret
	}
	return *o.CustomNet
}

// GetCustomNetOk returns a tuple with the CustomNet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Runtime) GetCustomNetOk() (*string, bool) {
	if o == nil || IsNil(o.CustomNet) {
		return nil, false
	}
	return o.CustomNet, true
}

// HasCustomNet returns a boolean if a field has been set.
func (o *Runtime) HasCustomNet() bool {
	if o != nil && !IsNil(o.CustomNet) {
		return true
	}

	return false
}

// SetCustomNet gets a reference to the given string and assigns it to the CustomNet field.
func (o *Runtime) SetCustomNet(v string) {
	o.CustomNet = &v
}

func (o Runtime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Runtime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomNet) {
		toSerialize["custom_net"] = o.CustomNet
	}
	return toSerialize, nil
}

type NullableRuntime struct {
	value *Runtime
	isSet bool
}

func (v NullableRuntime) Get() *Runtime {
	return v.value
}

func (v *NullableRuntime) Set(val *Runtime) {
	v.value = val
	v.isSet = true
}

func (v NullableRuntime) IsSet() bool {
	return v.isSet
}

func (v *NullableRuntime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuntime(val *Runtime) *NullableRuntime {
	return &NullableRuntime{value: val, isSet: true}
}

func (v NullableRuntime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuntime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


