/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// CommandStringInnerType struct for CommandStringInnerType
type CommandStringInnerType struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CommandStringInnerType) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CommandStringInnerType)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *CommandStringInnerType) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableCommandStringInnerType struct {
	value *CommandStringInnerType
	isSet bool
}

func (v NullableCommandStringInnerType) Get() *CommandStringInnerType {
	return v.value
}

func (v *NullableCommandStringInnerType) Set(val *CommandStringInnerType) {
	v.value = val
	v.isSet = true
}

func (v NullableCommandStringInnerType) IsSet() bool {
	return v.isSet
}

func (v *NullableCommandStringInnerType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommandStringInnerType(val *CommandStringInnerType) *NullableCommandStringInnerType {
	return &NullableCommandStringInnerType{value: val, isSet: true}
}

func (v NullableCommandStringInnerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommandStringInnerType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


