/*
Flowy Client API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiGetJobInfoGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiGetJobInfoGetRequest{}

// ApiGetJobInfoGetRequest struct for ApiGetJobInfoGetRequest
type ApiGetJobInfoGetRequest struct {
	JobId string `json:"jobId"`
}

type _ApiGetJobInfoGetRequest ApiGetJobInfoGetRequest

// NewApiGetJobInfoGetRequest instantiates a new ApiGetJobInfoGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiGetJobInfoGetRequest(jobId string) *ApiGetJobInfoGetRequest {
	this := ApiGetJobInfoGetRequest{}
	this.JobId = jobId
	return &this
}

// NewApiGetJobInfoGetRequestWithDefaults instantiates a new ApiGetJobInfoGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiGetJobInfoGetRequestWithDefaults() *ApiGetJobInfoGetRequest {
	this := ApiGetJobInfoGetRequest{}
	return &this
}

// GetJobId returns the JobId field value
func (o *ApiGetJobInfoGetRequest) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *ApiGetJobInfoGetRequest) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *ApiGetJobInfoGetRequest) SetJobId(v string) {
	o.JobId = v
}

func (o ApiGetJobInfoGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiGetJobInfoGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobId"] = o.JobId
	return toSerialize, nil
}

func (o *ApiGetJobInfoGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiGetJobInfoGetRequest := _ApiGetJobInfoGetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiGetJobInfoGetRequest)

	if err != nil {
		return err
	}

	*o = ApiGetJobInfoGetRequest(varApiGetJobInfoGetRequest)

	return err
}

type NullableApiGetJobInfoGetRequest struct {
	value *ApiGetJobInfoGetRequest
	isSet bool
}

func (v NullableApiGetJobInfoGetRequest) Get() *ApiGetJobInfoGetRequest {
	return v.value
}

func (v *NullableApiGetJobInfoGetRequest) Set(val *ApiGetJobInfoGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiGetJobInfoGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiGetJobInfoGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiGetJobInfoGetRequest(val *ApiGetJobInfoGetRequest) *NullableApiGetJobInfoGetRequest {
	return &NullableApiGetJobInfoGetRequest{value: val, isSet: true}
}

func (v NullableApiGetJobInfoGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiGetJobInfoGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


