/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommandStringInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommandStringInner{}

// CommandStringInner struct for CommandStringInner
type CommandStringInner struct {
	Type string `json:"type"`
	Value string `json:"value"`
}

type _CommandStringInner CommandStringInner

// NewCommandStringInner instantiates a new CommandStringInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommandStringInner(type_ string, value string) *CommandStringInner {
	this := CommandStringInner{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewCommandStringInnerWithDefaults instantiates a new CommandStringInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommandStringInnerWithDefaults() *CommandStringInner {
	this := CommandStringInner{}
	return &this
}

// GetType returns the Type field value
func (o *CommandStringInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CommandStringInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CommandStringInner) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *CommandStringInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CommandStringInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CommandStringInner) SetValue(v string) {
	o.Value = v
}

func (o CommandStringInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommandStringInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *CommandStringInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommandStringInner := _CommandStringInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommandStringInner)

	if err != nil {
		return err
	}

	*o = CommandStringInner(varCommandStringInner)

	return err
}

type NullableCommandStringInner struct {
	value *CommandStringInner
	isSet bool
}

func (v NullableCommandStringInner) Get() *CommandStringInner {
	return v.value
}

func (v *NullableCommandStringInner) Set(val *CommandStringInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCommandStringInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCommandStringInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommandStringInner(val *CommandStringInner) *NullableCommandStringInner {
	return &NullableCommandStringInner{value: val, isSet: true}
}

func (v NullableCommandStringInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommandStringInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


