/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf{}

// ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf struct for ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf
type ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf struct {
	Type string `json:"type"`
	Value string `json:"value"`
}

type _ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf

// NewApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf instantiates a new ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf(type_ string, value string) *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf {
	this := ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOfWithDefaults instantiates a new ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOfWithDefaults() *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf {
	this := ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf{}
	return &this
}

// GetType returns the Type field value
func (o *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) SetValue(v string) {
	o.Value = v
}

func (o ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf := _ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf)

	if err != nil {
		return err
	}

	*o = ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf(varApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf)

	return err
}

type NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf struct {
	value *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf
	isSet bool
}

func (v NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) Get() *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf {
	return v.value
}

func (v *NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) Set(val *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf(val *ApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) *NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf {
	return &NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf{value: val, isSet: true}
}

func (v NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiGetExectableJobPost200ResponseInnerCommandsInnerInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


