/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiGetExectableJobPost200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiGetExectableJobPost200ResponseInner{}

// ApiGetExectableJobPost200ResponseInner struct for ApiGetExectableJobPost200ResponseInner
type ApiGetExectableJobPost200ResponseInner struct {
	Id string `json:"id"`
	Commands [][]CommandStringInner `json:"commands"`
	StdinPath *string `json:"stdin_path,omitempty"`
	StdoutPath *string `json:"stdout_path,omitempty"`
	StderrPath *string `json:"stderr_path,omitempty"`
	Env map[string]string `json:"env"`
	Cwd string `json:"cwd"`
	ContainerOutdir string `json:"containerOutdir"`
	TmpDir string `json:"tmpDir"`
	RemoveTmpDir bool `json:"removeTmpDir"`
	Timelimit *int32 `json:"timelimit,omitempty"`
	OutputBindings []OutputBinding `json:"outputBindings"`
	Fileitems []MapperEnt `json:"fileitems"`
	Generatedlist []MapperEnt `json:"generatedlist"`
	InplaceUpdate bool `json:"inplace_update"`
	Networkaccess bool `json:"networkaccess"`
	OutputBaseDir *string `json:"outputBaseDir,omitempty"`
	DockerExec *string `json:"dockerExec,omitempty"`
	DockerImage *string `json:"dockerImage,omitempty"`
	Runtime Runtime `json:"runtime"`
}

type _ApiGetExectableJobPost200ResponseInner ApiGetExectableJobPost200ResponseInner

// NewApiGetExectableJobPost200ResponseInner instantiates a new ApiGetExectableJobPost200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiGetExectableJobPost200ResponseInner(id string, commands [][]CommandStringInner, env map[string]string, cwd string, containerOutdir string, tmpDir string, removeTmpDir bool, outputBindings []OutputBinding, fileitems []MapperEnt, generatedlist []MapperEnt, inplaceUpdate bool, networkaccess bool, runtime Runtime) *ApiGetExectableJobPost200ResponseInner {
	this := ApiGetExectableJobPost200ResponseInner{}
	this.Id = id
	this.Commands = commands
	this.Env = env
	this.Cwd = cwd
	this.ContainerOutdir = containerOutdir
	this.TmpDir = tmpDir
	this.RemoveTmpDir = removeTmpDir
	this.OutputBindings = outputBindings
	this.Fileitems = fileitems
	this.Generatedlist = generatedlist
	this.InplaceUpdate = inplaceUpdate
	this.Networkaccess = networkaccess
	this.Runtime = runtime
	return &this
}

// NewApiGetExectableJobPost200ResponseInnerWithDefaults instantiates a new ApiGetExectableJobPost200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiGetExectableJobPost200ResponseInnerWithDefaults() *ApiGetExectableJobPost200ResponseInner {
	this := ApiGetExectableJobPost200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ApiGetExectableJobPost200ResponseInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetId(v string) {
	o.Id = v
}

// GetCommands returns the Commands field value
func (o *ApiGetExectableJobPost200ResponseInner) GetCommands() [][]CommandStringInner {
	if o == nil {
		var ret [][]CommandStringInner
		return ret
	}

	return o.Commands
}

// GetCommandsOk returns a tuple with the Commands field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetCommandsOk() ([][]CommandStringInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Commands, true
}

// SetCommands sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetCommands(v [][]CommandStringInner) {
	o.Commands = v
}

// GetStdinPath returns the StdinPath field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInner) GetStdinPath() string {
	if o == nil || IsNil(o.StdinPath) {
		var ret string
		return ret
	}
	return *o.StdinPath
}

// GetStdinPathOk returns a tuple with the StdinPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetStdinPathOk() (*string, bool) {
	if o == nil || IsNil(o.StdinPath) {
		return nil, false
	}
	return o.StdinPath, true
}

// HasStdinPath returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInner) HasStdinPath() bool {
	if o != nil && !IsNil(o.StdinPath) {
		return true
	}

	return false
}

// SetStdinPath gets a reference to the given string and assigns it to the StdinPath field.
func (o *ApiGetExectableJobPost200ResponseInner) SetStdinPath(v string) {
	o.StdinPath = &v
}

// GetStdoutPath returns the StdoutPath field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInner) GetStdoutPath() string {
	if o == nil || IsNil(o.StdoutPath) {
		var ret string
		return ret
	}
	return *o.StdoutPath
}

// GetStdoutPathOk returns a tuple with the StdoutPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetStdoutPathOk() (*string, bool) {
	if o == nil || IsNil(o.StdoutPath) {
		return nil, false
	}
	return o.StdoutPath, true
}

// HasStdoutPath returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInner) HasStdoutPath() bool {
	if o != nil && !IsNil(o.StdoutPath) {
		return true
	}

	return false
}

// SetStdoutPath gets a reference to the given string and assigns it to the StdoutPath field.
func (o *ApiGetExectableJobPost200ResponseInner) SetStdoutPath(v string) {
	o.StdoutPath = &v
}

// GetStderrPath returns the StderrPath field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInner) GetStderrPath() string {
	if o == nil || IsNil(o.StderrPath) {
		var ret string
		return ret
	}
	return *o.StderrPath
}

// GetStderrPathOk returns a tuple with the StderrPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetStderrPathOk() (*string, bool) {
	if o == nil || IsNil(o.StderrPath) {
		return nil, false
	}
	return o.StderrPath, true
}

// HasStderrPath returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInner) HasStderrPath() bool {
	if o != nil && !IsNil(o.StderrPath) {
		return true
	}

	return false
}

// SetStderrPath gets a reference to the given string and assigns it to the StderrPath field.
func (o *ApiGetExectableJobPost200ResponseInner) SetStderrPath(v string) {
	o.StderrPath = &v
}

// GetEnv returns the Env field value
func (o *ApiGetExectableJobPost200ResponseInner) GetEnv() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetEnvOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Env, true
}

// SetEnv sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetEnv(v map[string]string) {
	o.Env = v
}

// GetCwd returns the Cwd field value
func (o *ApiGetExectableJobPost200ResponseInner) GetCwd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cwd
}

// GetCwdOk returns a tuple with the Cwd field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetCwdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cwd, true
}

// SetCwd sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetCwd(v string) {
	o.Cwd = v
}

// GetContainerOutdir returns the ContainerOutdir field value
func (o *ApiGetExectableJobPost200ResponseInner) GetContainerOutdir() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerOutdir
}

// GetContainerOutdirOk returns a tuple with the ContainerOutdir field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetContainerOutdirOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerOutdir, true
}

// SetContainerOutdir sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetContainerOutdir(v string) {
	o.ContainerOutdir = v
}

// GetTmpDir returns the TmpDir field value
func (o *ApiGetExectableJobPost200ResponseInner) GetTmpDir() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TmpDir
}

// GetTmpDirOk returns a tuple with the TmpDir field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetTmpDirOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TmpDir, true
}

// SetTmpDir sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetTmpDir(v string) {
	o.TmpDir = v
}

// GetRemoveTmpDir returns the RemoveTmpDir field value
func (o *ApiGetExectableJobPost200ResponseInner) GetRemoveTmpDir() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RemoveTmpDir
}

// GetRemoveTmpDirOk returns a tuple with the RemoveTmpDir field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetRemoveTmpDirOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoveTmpDir, true
}

// SetRemoveTmpDir sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetRemoveTmpDir(v bool) {
	o.RemoveTmpDir = v
}

// GetTimelimit returns the Timelimit field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInner) GetTimelimit() int32 {
	if o == nil || IsNil(o.Timelimit) {
		var ret int32
		return ret
	}
	return *o.Timelimit
}

// GetTimelimitOk returns a tuple with the Timelimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetTimelimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Timelimit) {
		return nil, false
	}
	return o.Timelimit, true
}

// HasTimelimit returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInner) HasTimelimit() bool {
	if o != nil && !IsNil(o.Timelimit) {
		return true
	}

	return false
}

// SetTimelimit gets a reference to the given int32 and assigns it to the Timelimit field.
func (o *ApiGetExectableJobPost200ResponseInner) SetTimelimit(v int32) {
	o.Timelimit = &v
}

// GetOutputBindings returns the OutputBindings field value
func (o *ApiGetExectableJobPost200ResponseInner) GetOutputBindings() []OutputBinding {
	if o == nil {
		var ret []OutputBinding
		return ret
	}

	return o.OutputBindings
}

// GetOutputBindingsOk returns a tuple with the OutputBindings field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetOutputBindingsOk() ([]OutputBinding, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputBindings, true
}

// SetOutputBindings sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetOutputBindings(v []OutputBinding) {
	o.OutputBindings = v
}

// GetFileitems returns the Fileitems field value
func (o *ApiGetExectableJobPost200ResponseInner) GetFileitems() []MapperEnt {
	if o == nil {
		var ret []MapperEnt
		return ret
	}

	return o.Fileitems
}

// GetFileitemsOk returns a tuple with the Fileitems field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetFileitemsOk() ([]MapperEnt, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fileitems, true
}

// SetFileitems sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetFileitems(v []MapperEnt) {
	o.Fileitems = v
}

// GetGeneratedlist returns the Generatedlist field value
func (o *ApiGetExectableJobPost200ResponseInner) GetGeneratedlist() []MapperEnt {
	if o == nil {
		var ret []MapperEnt
		return ret
	}

	return o.Generatedlist
}

// GetGeneratedlistOk returns a tuple with the Generatedlist field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetGeneratedlistOk() ([]MapperEnt, bool) {
	if o == nil {
		return nil, false
	}
	return o.Generatedlist, true
}

// SetGeneratedlist sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetGeneratedlist(v []MapperEnt) {
	o.Generatedlist = v
}

// GetInplaceUpdate returns the InplaceUpdate field value
func (o *ApiGetExectableJobPost200ResponseInner) GetInplaceUpdate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InplaceUpdate
}

// GetInplaceUpdateOk returns a tuple with the InplaceUpdate field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetInplaceUpdateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InplaceUpdate, true
}

// SetInplaceUpdate sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetInplaceUpdate(v bool) {
	o.InplaceUpdate = v
}

// GetNetworkaccess returns the Networkaccess field value
func (o *ApiGetExectableJobPost200ResponseInner) GetNetworkaccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Networkaccess
}

// GetNetworkaccessOk returns a tuple with the Networkaccess field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetNetworkaccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Networkaccess, true
}

// SetNetworkaccess sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetNetworkaccess(v bool) {
	o.Networkaccess = v
}

// GetOutputBaseDir returns the OutputBaseDir field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInner) GetOutputBaseDir() string {
	if o == nil || IsNil(o.OutputBaseDir) {
		var ret string
		return ret
	}
	return *o.OutputBaseDir
}

// GetOutputBaseDirOk returns a tuple with the OutputBaseDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetOutputBaseDirOk() (*string, bool) {
	if o == nil || IsNil(o.OutputBaseDir) {
		return nil, false
	}
	return o.OutputBaseDir, true
}

// HasOutputBaseDir returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInner) HasOutputBaseDir() bool {
	if o != nil && !IsNil(o.OutputBaseDir) {
		return true
	}

	return false
}

// SetOutputBaseDir gets a reference to the given string and assigns it to the OutputBaseDir field.
func (o *ApiGetExectableJobPost200ResponseInner) SetOutputBaseDir(v string) {
	o.OutputBaseDir = &v
}

// GetDockerExec returns the DockerExec field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInner) GetDockerExec() string {
	if o == nil || IsNil(o.DockerExec) {
		var ret string
		return ret
	}
	return *o.DockerExec
}

// GetDockerExecOk returns a tuple with the DockerExec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetDockerExecOk() (*string, bool) {
	if o == nil || IsNil(o.DockerExec) {
		return nil, false
	}
	return o.DockerExec, true
}

// HasDockerExec returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInner) HasDockerExec() bool {
	if o != nil && !IsNil(o.DockerExec) {
		return true
	}

	return false
}

// SetDockerExec gets a reference to the given string and assigns it to the DockerExec field.
func (o *ApiGetExectableJobPost200ResponseInner) SetDockerExec(v string) {
	o.DockerExec = &v
}

// GetDockerImage returns the DockerImage field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInner) GetDockerImage() string {
	if o == nil || IsNil(o.DockerImage) {
		var ret string
		return ret
	}
	return *o.DockerImage
}

// GetDockerImageOk returns a tuple with the DockerImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetDockerImageOk() (*string, bool) {
	if o == nil || IsNil(o.DockerImage) {
		return nil, false
	}
	return o.DockerImage, true
}

// HasDockerImage returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInner) HasDockerImage() bool {
	if o != nil && !IsNil(o.DockerImage) {
		return true
	}

	return false
}

// SetDockerImage gets a reference to the given string and assigns it to the DockerImage field.
func (o *ApiGetExectableJobPost200ResponseInner) SetDockerImage(v string) {
	o.DockerImage = &v
}

// GetRuntime returns the Runtime field value
func (o *ApiGetExectableJobPost200ResponseInner) GetRuntime() Runtime {
	if o == nil {
		var ret Runtime
		return ret
	}

	return o.Runtime
}

// GetRuntimeOk returns a tuple with the Runtime field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInner) GetRuntimeOk() (*Runtime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Runtime, true
}

// SetRuntime sets field value
func (o *ApiGetExectableJobPost200ResponseInner) SetRuntime(v Runtime) {
	o.Runtime = v
}

func (o ApiGetExectableJobPost200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiGetExectableJobPost200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["commands"] = o.Commands
	if !IsNil(o.StdinPath) {
		toSerialize["stdin_path"] = o.StdinPath
	}
	if !IsNil(o.StdoutPath) {
		toSerialize["stdout_path"] = o.StdoutPath
	}
	if !IsNil(o.StderrPath) {
		toSerialize["stderr_path"] = o.StderrPath
	}
	toSerialize["env"] = o.Env
	toSerialize["cwd"] = o.Cwd
	toSerialize["containerOutdir"] = o.ContainerOutdir
	toSerialize["tmpDir"] = o.TmpDir
	toSerialize["removeTmpDir"] = o.RemoveTmpDir
	if !IsNil(o.Timelimit) {
		toSerialize["timelimit"] = o.Timelimit
	}
	toSerialize["outputBindings"] = o.OutputBindings
	toSerialize["fileitems"] = o.Fileitems
	toSerialize["generatedlist"] = o.Generatedlist
	toSerialize["inplace_update"] = o.InplaceUpdate
	toSerialize["networkaccess"] = o.Networkaccess
	if !IsNil(o.OutputBaseDir) {
		toSerialize["outputBaseDir"] = o.OutputBaseDir
	}
	if !IsNil(o.DockerExec) {
		toSerialize["dockerExec"] = o.DockerExec
	}
	if !IsNil(o.DockerImage) {
		toSerialize["dockerImage"] = o.DockerImage
	}
	toSerialize["runtime"] = o.Runtime
	return toSerialize, nil
}

func (o *ApiGetExectableJobPost200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"commands",
		"env",
		"cwd",
		"containerOutdir",
		"tmpDir",
		"removeTmpDir",
		"outputBindings",
		"fileitems",
		"generatedlist",
		"inplace_update",
		"networkaccess",
		"runtime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiGetExectableJobPost200ResponseInner := _ApiGetExectableJobPost200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiGetExectableJobPost200ResponseInner)

	if err != nil {
		return err
	}

	*o = ApiGetExectableJobPost200ResponseInner(varApiGetExectableJobPost200ResponseInner)

	return err
}

type NullableApiGetExectableJobPost200ResponseInner struct {
	value *ApiGetExectableJobPost200ResponseInner
	isSet bool
}

func (v NullableApiGetExectableJobPost200ResponseInner) Get() *ApiGetExectableJobPost200ResponseInner {
	return v.value
}

func (v *NullableApiGetExectableJobPost200ResponseInner) Set(val *ApiGetExectableJobPost200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiGetExectableJobPost200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiGetExectableJobPost200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiGetExectableJobPost200ResponseInner(val *ApiGetExectableJobPost200ResponseInner) *NullableApiGetExectableJobPost200ResponseInner {
	return &NullableApiGetExectableJobPost200ResponseInner{value: val, isSet: true}
}

func (v NullableApiGetExectableJobPost200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiGetExectableJobPost200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


